# .github/workflows/update.yaml
name: Atualizar CSV Rota Pharma

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar main.py
      run: python main.py

    - name: Commit e push CSV atualizado
      run: |
        git config user.name "github-actions"
        git config user.email "actions@users.noreply.github.com"
        git add posicoes.csv
        git commit -m "Atualiza CSV automaticamente"
        git push
      continue-on-error: true
